export const defaultRoles = [
  { title: 'CEO', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 1 },
  { title: 'General Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 2 },
  { title: 'Chief Financial Officer', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 3 },
  { title: 'Controller/Accounting Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 4 },
  { title: 'Office Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 5 },
  { title: 'Human Resources Director', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 6 },
  { title: 'Information Systems/Network Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 7 },
  { title: 'IT Specialist', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 8 },
  { title: 'Accounting/Invoicing Clerk', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 9 },
  { title: 'Payroll Accountant/Supervisor', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 10 },
  { title: 'Sales Director/VP of Sales', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 11 },
  { title: 'Domestic Sales Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 12 },
  { title: 'Domestic Sales Representative', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 13 },
  { title: 'Export Sales Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 14 },
  { title: 'Export Sales Representative', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 15 },
  { title: 'Sales Assistant', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 16 },
  { title: 'Marketing Director/VP of Marketing', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 17 },
  { title: 'Marketing/Promotion Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 18 },
  { title: 'Marketing/Data Analyst', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 19 },
  { title: 'Category Management', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 20 },
  { title: 'Quality Control Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 21 },
  { title: 'Quality Control Specialist', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 22 },
  { title: 'Inventory/Production Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 23 },
  { title: 'Inventory/Production Employee', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 24 },
  { title: 'Logistics Manager', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 25 },
  { title: 'Logistics Employee', type: 'marketing' as const, payType: 'exempt' as const, sortOrder: 26 },
  { title: 'CEO', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 27 },  
  { title: 'General Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 28 },
  { title: 'Executive Assistant', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 29 },
  { title: 'Controller', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 30 },
  { title: 'Office Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 31 },
  { title: 'Chief Financial Officer', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 32 },
  { title: 'Human Resource Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 33 },
  { title: 'HR Assistant Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 34 },
  { title: 'Information Systems/Network Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 35 },
  { title: 'Grower/Fruit Accountant', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 36 },
  { title: 'Accounts Payable Accountant', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 37 },
  { title: 'Payroll Accountant', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 38 },
  { title: 'Purchasing/Distribution Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 39 },
  { title: 'Purchasing Agent/Inventory Control Analyst', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 40 },
  { title: 'Receptionist', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 41 },
  { title: 'Operations Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 42 },
  { title: 'Production Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 43 },
  { title: 'Food Safety Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 44 },
  { title: 'IT Specialist', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 45 },
  { title: 'Dispatcher', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 46 },
  { title: 'Safety/Compliance Officer', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 47 },
  { title: 'Quality Control Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 48 },
  { title: 'Field Services Manager', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 49 },
  { title: 'Fieldman', type: 'warehouse' as const, payType: 'exempt' as const, sortOrder: 50 },
  { title: 'Sanitation Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 52 },
  { title: 'Line Sanitation Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 53 },
  { title: 'Forklift Operator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 54 },
  { title: 'Forklift Mechanic', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 55 },
  { title: 'Auto/Truck Mechanic', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 56 },
  { title: 'Warehouse Equipment Mechanic', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 57 },
  { title: 'Quality Control Technician', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 58 },
  { title: 'Line Sanitation', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 59 },
  { title: 'Sanitation Lead', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 60 },
  { title: 'Sorting Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 61 },
  { title: 'Packing Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 62 },
  { title: 'Floor Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 63 },
  { title: 'Supply Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 64 },
  { title: 'Sorter', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 65 },
  { title: 'Sizer Operator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 66 },
  { title: 'Bin Filler Operator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 67 },
  { title: 'Bin Dumper', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 68 },
  { title: 'Packer', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 69 },
  { title: 'Box Machine Operator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 70 },
  { title: 'Stamper', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 71 },
  { title: 'Packing Line Attendant', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 72 },
  { title: 'Packing Line Mechanic', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 73 },
  { title: 'Bagger', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 74 },
  { title: 'Bin Repair Technician', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 75 },
  { title: 'Glue & Strap Machine Operator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 76 },
  { title: 'Truck Driver', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 77 },
  { title: 'Receiving Clerk', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 78 },
  { title: 'Receiving Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 79 },
  { title: 'Refrigeration Mechanic', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 80 },
  { title: 'Refrigeration Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 81 },
  { title: 'Shipping Supervisor', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 82 },
  { title: 'Segregator', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 83 },
  { title: 'Loader', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 84 },
  { title: 'Shipping Clerk', type: 'warehouse' as const, payType: 'non-exempt' as const, sortOrder: 85 },
  { title: 'CEO', type: 'both' as const, payType: 'exempt' as const, sortOrder: 1 },
  { title: 'General Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 2 },
  { title: 'Chief Financial Officer', type: 'both' as const, payType: 'exempt' as const, sortOrder: 3 },
  { title: 'Controller/Accounting Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 4 },
  { title: 'Office Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 5 },
  { title: 'Human Resources Director', type: 'both' as const, payType: 'exempt' as const, sortOrder: 6 },
  { title: 'Human Resource Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 7 },
  { title: 'HR Assistant Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 8 },
  { title: 'Information Systems/Network Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 9 },
  { title: 'IT Specialist', type: 'both' as const, payType: 'exempt' as const, sortOrder: 10 },
  { title: 'Accounting/Invoicing Clerk', type: 'both' as const, payType: 'exempt' as const, sortOrder: 11 },
  { title: 'Payroll Accountant/Supervisor', type: 'both' as const, payType: 'exempt' as const, sortOrder: 12 },
  { title: 'Sales Director/VP of Sales', type: 'both' as const, payType: 'exempt' as const, sortOrder: 13 },
  { title: 'Domestic Sales Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 14 },
  { title: 'Domestic Sales Representative', type: 'both' as const, payType: 'exempt' as const, sortOrder: 15 },
  { title: 'Export Sales Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 16 },
  { title: 'Export Sales Representative', type: 'both' as const, payType: 'exempt' as const, sortOrder: 17 },
  { title: 'Sales Assistant', type: 'both' as const, payType: 'exempt' as const, sortOrder: 18 },
  { title: 'Marketing Director/VP of Marketing', type: 'both' as const, payType: 'exempt' as const, sortOrder: 19 },
  { title: 'Marketing/Promotion Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 20 },
  { title: 'Marketing/Data Analyst', type: 'both' as const, payType: 'exempt' as const, sortOrder: 21 },
  { title: 'Category Management', type: 'both' as const, payType: 'exempt' as const, sortOrder: 22 },
  { title: 'Quality Control Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 23 },
  { title: 'Quality Control Specialist', type: 'both' as const, payType: 'exempt' as const, sortOrder: 24 },
  { title: 'Inventory/Production Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 25 },
  { title: 'Inventory/Production Employee', type: 'both' as const, payType: 'exempt' as const, sortOrder: 26 },
  { title: 'Logistics Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 27 },
  { title: 'Logistics Employee', type: 'both' as const, payType: 'exempt' as const, sortOrder: 28 },
  { title: 'Grower/Fruit Accountant', type: 'both' as const, payType: 'exempt' as const, sortOrder: 29 },
  { title: 'Accounts Payable Accountant', type: 'both' as const, payType: 'exempt' as const, sortOrder: 30 },
  { title: 'Payroll Accountant', type: 'both' as const, payType: 'exempt' as const, sortOrder: 31 },
  { title: 'Purchasing/Distribution Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 32 },
  { title: 'Purchasing Agent/Inventory Control Analyst', type: 'both' as const, payType: 'exempt' as const, sortOrder: 33 },
  { title: 'Receptionist', type: 'both' as const, payType: 'exempt' as const, sortOrder: 34 },
  { title: 'Operations Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 35 },
  { title: 'Production Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 36 },
  { title: 'Food Safety Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 37 },
  { title: 'Safety/Compliance Officer', type: 'both' as const, payType: 'exempt' as const, sortOrder: 38 },
  { title: 'Field Services Manager', type: 'both' as const, payType: 'exempt' as const, sortOrder: 39 },
  { title: 'Fieldman', type: 'both' as const, payType: 'exempt' as const, sortOrder: 40 },
  { title: 'Sanitation Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 42 },
  { title: 'Line Sanitation Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 43 },
  { title: 'Forklift Operator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 44 },
  { title: 'Forklift Mechanic', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 45 },
  { title: 'Auto/Truck Mechanic', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 46 },
  { title: 'Warehouse Equipment Mechanic', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 47 },
  { title: 'Quality Control Technician', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 48 },
  { title: 'Line Sanitation', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 49 },
  { title: 'Sanitation Lead', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 50 },
  { title: 'Sorting Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 51 },
  { title: 'Packing Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 52 },
  { title: 'Floor Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 53 },
  { title: 'Supply Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 54 },
  { title: 'Sorter', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 55 },
  { title: 'Sizer Operator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 56 },
  { title: 'Bin Filler Operator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 57 },
  { title: 'Bin Dumper', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 58 },
  { title: 'Packer', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 59 },
  { title: 'Box Machine Operator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 60 },
  { title: 'Stamper', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 61 },
  { title: 'Packing Line Attendant', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 62 },
  { title: 'Packing Line Mechanic', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 63 },
  { title: 'Bagger', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 64 },
  { title: 'Bin Repair Technician', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 65 },
  { title: 'Glue & Strap Machine Operator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 66 },
  { title: 'Truck Driver', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 67 },
  { title: 'Receiving Clerk', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 68 },
  { title: 'Receiving Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 69 },
  { title: 'Refrigeration Mechanic', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 70 },
  { title: 'Refrigeration Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 71 },
  { title: 'Shipping Supervisor', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 72 },
  { title: 'Segregator', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 73 },
  { title: 'Loader', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 74 },
  { title: 'Shipping Clerk', type: 'both' as const, payType: 'non-exempt' as const, sortOrder: 75 }
];
